// document.addEventListener('DOMContentLoaded', () => {
//     // Show the home section by default
//     showSection('home');
// });


// // document.querySelector('.contact-us-btn').addEventListener('click', function(event) {
// //     event.preventDefault();
// //     const sectionId = this.getAttribute('href').substring(1);
// //     showSection(sectionId);
// // });


// // Event listener for the "All Cars" button
//     // document.querySelector('.all-cars-button').addEventListener('click', function(event) {
//     //     event.preventDefault();
//     //     const sectionId = this.getAttribute('href').substring(1);
//     //     showSection(sectionId);
//     // });


    
// // Event listener for the "New Arrivals" button
// document.querySelector('.new-arrivals-button').addEventListener('click', function(event) {
//     event.preventDefault();
//     const sectionId = this.getAttribute('href').substring(1);
//     showSection(sectionId);
// });

// // Event listener for the "Used Cars" button
// document.querySelector('.used-cars-button').addEventListener('click', function(event) {
//     event.preventDefault();
//     const sectionId = this.getAttribute('href').substring(1);
//     showSection(sectionId);
// });

// function showSection(sectionId) {
//     // Hide all sections
//     const sections = document.querySelectorAll('.content-section');
//     sections.forEach(section => {
//         section.classList.remove('active');
//     });

//     // Show the selected section
//     document.getElementById(sectionId).classList.add('active');
    
//     // Scroll to the top of the page
//     window.scrollTo({ top: 0, behavior: 'smooth' });

//     // Close any open modal when changing sections
//     closeModal('car-description');

//     // Show or hide the header based on the section
//     const header = document.querySelector('header');
//     if (sectionId === 'home') {
//         header.style.display = 'block';
//     } else {
//         header.style.display = 'none';
//     }
// }

function openModal(modalId) {
    document.getElementById(`${modalId}-modal`).style.display = 'block';
}

function closeModal(modalId) {
    document.getElementById(`${modalId}-modal`).style.display = 'none';
}

function openCarDescription(carId) {
    const carDescriptions = {
        car2: {
            title: "Audi A4 40 TFSI S tronic S-line Avant 150 kW",
            price: "61 199 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Audi",
            description4: "Model: A4",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1595 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 150kW",
            description18: "Engine volume: 1984 cm3",
            description19: "Consumption: 5.9 l/100km (combined)",
            description20: "CO2 emissions: 135g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 0 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: Germany",
            image: "car2.jpg"
        },
        car3: {
            title: "BMW 330 Touring M Sport xDrive 137 kW",
            price: "71 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: France",
            description3: "Brand: BMW",
            description4: "Model: 330",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Other interior material",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Other fuels",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 137 kW",
            description18: "Engine volume: 1998 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 35 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 5/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car3.jpg"
        },
        car4: {
            title: "Peugeot 3008 BlueHDi 130 S&S EAT8 Allure 96 kW",
            price: "37 099 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Peugeot",
            description4: "Model: 3008",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 96 kW",
            description18: "Engine volume: 1499 cm3",
            description19: "Consumption: 5.5 l/100km (combined)",
            description20: "CO2 emissions: 104 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 0 km",
            description24: "First registration: 3/2024",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car4.jpg"
        },
        car5: {
            title: "Alfa Romeo Giulia 2.0 Veloce 206 kW",
            price: "57 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Austria",
            description3: "Brand: Alfa Romeo",
            description4: "Model: Giulia",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 206 kW",
            description18: "Engine volume: 1995 cm3",
            description19: "Consumption: 7.6 l/100km (combined)",
            description20: "CO2 emissions: 176 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 5 km",
            description24: "First registration: 3/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car5.jpg"
        },
        car6: {
            title: "Ford Focus 1.0 ACTIVE 92 kW",
            price: "23 249 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Ford",
            description4: "Model: Focus",
            description5: "Body color: Blue",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Other interior material",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 92 kW",
            description18: "Engine volume: 998 cm3",
            description19: "Consumption: 4.3 l/100km (combined) | 4.8 l/100km (city) | 3.6 l/100km",
            description20: "CO2 emissions: 94 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 10/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car6.jpg"
        },
        car7: {
            title: "Jeep Renegade 1.0 Limited 88 kW",
            price: "24 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Jeep",
            description4: "Model: Renegade",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1320 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 88 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 5.6 l/100km (combined)",
            description20: "CO2 emissions: 128 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 1 km",
            description24: "First registration: 1/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car7.jpg"
        },
        car10: {
            title: "Volkswagen Polo 1.0 TSI DSG 70 kW",
            price: "23 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Volkswagen",
            description4: "Model: Polo",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1199 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 70 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 5.6 l/100km",
            description20: "CO2 emissions: 105 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 10/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car10.jpg"
        },
        car11: {
            title: "Suzuki Ignis 61 kW",
            price: "18 199 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Suzuki",
            description4: "Model: Ignis",
            description5: "Body color: Red",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 4",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 61 kW",
            description18: "Engine volume: 1197 cm3",
            description19: "Consumption: 5 l/100km (combined)",
            description20: "CO2 emissions: 89 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 3/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car11.jpg"
        },
        car12: {
            title: "Ford Puma ST-Line X 92 kW",
            price: "32 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Ford",
            description4: "Model: Cougar",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Gray interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1334 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 92 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 6.1 l/100km (combined)",
            description20: "CO2 emissions: 113 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 0 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: Germany",
            image: "car12.jpg"
        },
        car13: {
            title: "Volkswagen Golf 1.0 eTSI Life DSG 81 kW",
            price: "28 749 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Volkswagen",
            description4: "Model: Golf",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1360 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 81 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 5.2 l/100km (combined)",
            description20: "CO2 emissions: 108 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car13.jpg"
        },
        car14: {
            title: "Kia Sorento 2.2 Spirit AWD 142 kW",
            price: "49 649 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Kia",
            description4: "Model: Sorento",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 142 kW",
            description18: "Engine volume: 2151 cm3",
            description19: "Consumption: 6.7 l/100km (combined)",
            description20: "CO2 emissions: 174 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 12 km",
            description24: "First registration: 9/2023",
            description25: "Condition: Demonstration vehicle",
            description26: "Country of origin: undefined",
            image: "car14.jpg"
        },
        car15: {
            title: "BMW 840i Gran 246 kW",
            price: "162 599 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Netherlands",
            description3: "Brand: BMW",
            description4: "Model: 840",
            description5: "Body color: Blue",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Coupe",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: undefined",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 246 kW",
            description18: "Engine volume: undefined",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 0 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 15 km",
            description24: "First registration: 1/2024",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car15.jpg"
        },
        car16: {
            title: "Skoda Fabia 59 kW",
            price: "17 899 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Skoda",
            description4: "Model: Fabia",
            description5: "Body color: Blue",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 59 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 6.1 l/100km (combined)",
            description20: "CO2 emissions: 139 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 1 km",
            description24: "First registration: 4/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car16.jpg"
        },
        car17: {
            title: "Porsche Cayenne E-Hybrid 346 kW",
            price: "158 699 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Porsche",
            description4: "Model: Cayenne",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 2500 kg",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 346 kW",
            description18: "Engine volume: 2995 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 0 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 0 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: Germany",
            image: "car17.jpg"
        },
        car18: {
            title: "Toyota C-HR 2.0 145 kW",
            price: "39 149 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Toyota",
            description4: "Model: C-HR",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 145 kW",
            description18: "Engine volume: 2000 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 92 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car18.jpg"
        },
        car19: {
            title: "Opel Astra 1.2 Turbo 81 kW",
            price: "20 349 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Czech Republic",
            description3: "Brand: Opel",
            description4: "Model: Astra",
            description5: "Body color: Dark yellow",
            description6: "Color type: Metallization",
            description7: "Interior color: undefined",
            description8: "Interior material: undefined",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 81 kW",
            description18: "Engine volume: 1199 cm3",
            description19: "Consumption: 4.3 l/100km (combined)",
            description20: "CO2 emissions: 99 g/km",
            description21: "Emission class: undefined",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 3 km",
            description24: "First registration: 1/2023",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car19.jpg"
        },
        car20: {
            title: "BMW 116i 80 kW",
            price: "30 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: BMW",
            description4: "Model: 116",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Alcantara interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 80 kW",
            description18: "Engine volume: 1499 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 0 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 30 km",
            description24: "First registration: 3/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car20.jpg"
        },
        car21: {
            title: "Toyota Corolla 1.8 Hybrid 103 kW",
            price: "32 149 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Toyota",
            description4: "Model: Corolla",
            description5: "Body color: Red",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 103 kW",
            description18: "Engine volume: 1798 cm3",
            description19: "Consumption: 3.6 l/100km (combined)",
            description20: "CO2 emissions: 89 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 15 km",
            description24: "First registration: 1/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car21.jpg"
        },
        car22: {
            title: "Skoda Fabia 85 kW",
            price: "27 099 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Skoda",
            description4: "Model: Fabia",
            description5: "Body color: Silver",
            description6: "Color type: Metallization",
            description7: "Interior color: Gray interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1195 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 85 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 0 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: Germany",
            image: "car22.jpg"
        },
        car23: {
            title: "Suzuki Jimny 75 kW",
            price: "28 999 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Suzuki",
            description4: "Model: Jimny",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 2/3 doors",
            description11: "Number of seats: 2",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x4",
            description17: "Power: 75 kW",
            description18: "Engine volume: 1462 cm3",
            description19: "Consumption: 6.1 l/100km (combined)",
            description20: "CO2 emissions: 138 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 12/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car23.jpg"
        },
        car24: {
            title: "Ford Ranger 150 kW",
            price: "55 099 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Ford",
            description4: "Model: Ranger",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Other interior material",
            description9: "Car body: Pick-up",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 2436 kg",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 150 kW",
            description18: "Engine volume: 1996 cm3",
            description19: "Consumption: 6.9 l/100km (combined)",
            description20: "CO2 emissions: 179 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 11/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car24.jpg"
        },
        car25: {
            title: "Volkswagen Polo 70 kW",
            price: "20 699 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Volkswagen",
            description4: "Model: Polo",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1172 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 70 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 4.6 l/100km (combined)",
            description20: "CO2 emissions: 106 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 1 km",
            description24: "First registration: 10/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car25.jpg"
        },
        car26: {
            title: "Suzuki SX4 S-Cross 75 kW",
            price: "27 599 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Suzuki",
            description4: "Model: SX4 S-Cross",
            description5: "Body color: Blue",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Farbic interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: undefined",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 75 kW",
            description18: "Engine volume: 1462 cm3",
            description19: "Consumption: 5.2 l/100km (combined)",
            description20: "CO2 emissions: 118 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 3/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car26.jpg"
        },
        car27: {
            title: "Alfa Romeo Tonale 118 kW",
            price: "39 749 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: Alfa Romeo",
            description4: "Model: Tonal",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1525 kg",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 118 kW",
            description18: "Engine volume: 1469 cm3",
            description19: "Consumption: 6 l/100km (combined)",
            description20: "CO2 emissions: 130 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 1 km",
            description24: "First registration: 6/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car27.jpg"
        },
        car28: {
            title: "Dacia Sandero 74 kW",
            price: "18 049 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Dacia",
            description4: "Model: Sandero",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Gray interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1203 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 74 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 5.3 l/100km (combined)",
            description20: "CO2 emissions: 120 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 10 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: Germany",
            image: "car28.jpg"
        },
        car29: {
            title: "Seat Arona 1.0 TSI DSG 81 kW",
            price: "33 399 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Seat",
            description4: "Model: Arona",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 81 kW",
            description18: "Engine volume: 999 cm3",
            description19: "Consumption: 4.8 l/100km (combined)",
            description20: "CO2 emissions: 109 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 14 km",
            description24: "First registration: 3/2024",
            description25: "Condition: Demonstration vehicle",
            description26: "Country of origin: undefined",
            image: "car29.jpg"
        },
        car30: {
            title: "Skoda Octavia Combi 1.5 eTSI DSG 110 kW",
            price: "37 899 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Skoda",
            description4: "Model: Octavia",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1498 cm3",
            description19: "Consumption: 5.5 l/100km (combined) | 5.4 l/100km (city) | 4.8 l/100km",
            description20: "CO2 emissions: 117 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 20 km",
            description24: "First registration: 2/2024",
            description25: "Condition: New",
            description26: "Country of origin: undefined",
            image: "car30.jpg"
        },
        car33: {
            title: "Audi A6 Allroad 255 kW",
            price: "59 699 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Poland",
            description3: "Brand: Audi",
            description4: "Model: A6 Allroad",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: undefined",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 255 kW",
            description18: "Engine volume: 2967 cm3",
            description19: "Consumption: 6.4 l/100km (combined)",
            description20: "CO2 emissions: 168 g/km",
            description21: "Emission class: ",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 111 397 km",
            description24: "First registration: 1/2019",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car33.jpg"
        },
        car34: {
            title: "Skoda Kodiaq 180 kW",
            price: "46 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Skoda",
            description4: "Model: Kodiaq",
            description5: "Body color: Red",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 180 kW",
            description18: "Engine volume: 1984 cm3",
            description19: "Consumption: 7.9 l/100km (combined)",
            description20: "CO2 emissions: 157 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 47 680 km",
            description24: "First registration: 3/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car34.jpg"
        },
        car35: {
            title: "Skoda Superb Combi 2.0 TDI Ambition 110 kW",
            price: "29 699 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Skoda",
            description4: "Model: Superb",
            description5: "Body color: Silver",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1968 cm3",
            description19: "Consumption: 4.8 l/100km (combined)",
            description20: "CO2 emissions: 125 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 52 450 km",
            description24: "First registration: 3/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car35.jpg"
        },
        car36: {
            title: "Skoda Octavia 2.0 TDI DSG Style 110 kW",
            price: "31 349 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Czech Republic",
            description3: "Brand: Skoda",
            description4: "Model: Octavia",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: undefined",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1968 cm3",
            description19: "Consumption: 4.4 l/100km (combined)",
            description20: "CO2 emissions: 98 g/km",
            description21: "Emission class: undefined",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 20 150 km",
            description24: "First registration: 3/2023",
            description25: "Condition: Used",
            description26: "Country of origin: Czech Republic",
            image: "car36.jpg"
        },
        car37: {
            title: "Volkswagen Passat Variant 2.0 TDI R-Line DSG 147 kW",
            price: "31 799 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Volkswagen",
            description4: "Model: Passat",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 147 kW",
            description18: "Engine volume: 1968 cm3",
            description19: "Consumption: 5.5 l/100km (combined)",
            description20: "CO2 emissions: 124 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 81 250 km",
            description24: "First registration: 2/2021",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car37.jpg"
        },
        car38: {
            title: "Land Rover Discovery 177 kW",
            price: "47 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Land Rover",
            description4: "Model: Discovery",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 7",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 177 kW",
            description18: "Engine volume: 1999 cm3",
            description19: "Consumption: 7.4 l/100km (combined)",
            description20: "CO2 emissions: 194 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 27 407 km",
            description24: "First registration: 3/2019",
            description25: "Condition: used",
            description26: "Country of origin: undefined",
            image: "car38.jpg"
        },
        car39: {
            title: "Audi A6 45 TDI quattro Avant 170 kW",
            price: "28 399 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Audi",
            description4: "Model: A6",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 170 kW",
            description18: "Engine volume: 2967 cm3",
            description19: "Consumption: 5.8 l/100km (combined)",
            description20: "CO2 emissions: 151 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 155 000 km",
            description24: "First registration: 11/2018",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car39.jpg"
        },
        car40: {
            title: "Audi A3 1.4 TFSIe e-tron S tronic Sportback 150 kW",
            price: "22 149 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: France",
            description3: "Brand: Audi",
            description4: "Model: A3",
            description5: "Body color: Silver",
            description6: "Color type: Metallization",
            description7: "Interior color: undefined",
            description8: "Interior material: undefined",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 150 kW",
            description18: "Engine volume: 1395 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 38 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 83 000 km",
            description24: "First registration: 6/2018",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car40.jpg"
        },
        car41: {
            title: "Peugeot 508 SW GT 165 kW",
            price: "27 349 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Peugeot",
            description4: "Model: 508",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Alcantara interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 165 kW",
            description18: "Engine volume: 1598 cm3",
            description19: "Consumption: 5.4 l/100km (combined)",
            description20: "CO2 emissions: 124 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 43 700 km",
            description24: "First registration: 11/2019",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car41.jpg"
        },
        car42: {
            title: "Audi A6 55 TFSIe quattro Avant 273 kW",
            price: "74 599 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Belgium",
            description3: "Brand: Audi",
            description4: "Model: A6",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Station wagon",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Hybrid",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 273 kW",
            description18: "Engine volume: 1984 cm3",
            description19: "Consumption: 1.5 l/100km (combined)",
            description20: "CO2 emissions: 36 g/km",
            description21: "Emission class: Euro 6d-TEMP",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 23 650 km",
            description24: "First registration: 3/2023",
            description25: "Condition: Demonstration vehicle",
            description26: "Country of origin: Belgium",
            image: "car42.jpg"
        },
        car43: {
            title: "BMW 420i Coupe 135 kW",
            price: "46 449 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: BMW",
            description4: "Model: 420",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Coupe",
            description10: "Number of doors: 2/3 doors",
            description11: "Number of seats: 4",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 135 kW",
            description18: "Engine volume: 1998 cm3",
            description19: "Consumption: 5.3 l/100km (combined)",
            description20: "CO2 emissions: 143 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 14 987 km",
            description24: "First registration: 7/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car43.jpg"
        },
        car44: {
            title: "BMW 116d 85 kW",
            price: "29 349 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Austria",
            description3: "Brand: BMW",
            description4: "Model: 116",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Gray interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 85 kW",
            description18: "Engine volume: 1496 cm3",
            description19: "Consumption: 3.8 l/100km (combined)",
            description20: "CO2 emissions: 121 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 25 834 km",
            description24: "First registration: 12/2022",
            description25: "Condition: used",
            description26: "Country of origin: undefined",
            image: "car44.jpg"
        },
        car45: {
            title: "BMW 118d 110 kW",
            price: "35 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: BMW",
            description4: "Model: 118",
            description5: "Body color: Blue",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1475 kg",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1995 cm3",
            description19: "Consumption: 4.1 l/100km (combined)",
            description20: "CO2 emissions: 108 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 29 000 km",
            description24: "First registration: 3/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car45.jpg"
        },
        car46: {
            title: "BMW 118d 110 kW",
            price: "31 949 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: BMW",
            description4: "Model: 118",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1475 kg",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1995 cm3",
            description19: "Consumption: 4.1 l/100km (combined)",
            description20: "CO2 emissions: 108 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 24 000 km",
            description24: "First registration: 5/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car46.jpg"
        },
        car47: {
            title: "Opel Mokka 1.2 Turbo Elegance 96 kW",
            price: "23 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Opel",
            description4: "Model: Mokka",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 96 kW",
            description18: "Engine volume: 1199 cm3",
            description19: "Consumption: 4.5 l/100km (combined)",
            description20: "CO2 emissions: 102 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 11 641",
            description24: "First registration: 1/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car47.jpg"
        },
        car48: {
            title: "Peugeot 308 1.5 BlueHDi 130 Active 96 kW",
            price: "14 649 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Spain",
            description3: "Brand: Peugeot",
            description4: "Model: 308",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Other interior material",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1255 kg",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 96 kW",
            description18: "Engine volume: 1499 cm3",
            description19: "Consumption: 4.7 l/100km (combined)",
            description20: "CO2 emissions: 91 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 96 500 km",
            description24: "First registration: 3/2021",
            description25: "Condition: Used",
            description26: "Country of origin: Spain",
            image: "car48.jpg"
        },
        car49: {
            title: "McLaren GT 456 kW",
            price: "179 399 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: McLaren",
            description4: "Model: GT",
            description5: "Body color: Silver",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Coupe",
            description10: "Number of doors: 2/3 doors",
            description11: "Number of seats: 2",
            description12: "Weight: 1605 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 456 kW",
            description18: "Engine volume: 3994 cm3",
            description19: "Consumption: 10.8 l/100km (combined)",
            description20: "CO2 emissions: 270 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 4241",
            description24: "First registration: 6/2022",
            description25: "Condition: Used",
            description26: "Country of origin: Italy",
            image: "car49.jpg"
        },
        car50: {
            title: "Mazda MX-30 107 kW",
            price: "21 099 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Mazda",
            description4: "Model: MX-30",
            description5: "Body color: Black",
            description6: "Color type: Metallization",
            description7: "Interior color: Gray interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Electricity",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 107 kW",
            description18: "Engine volume: 830 cm3",
            description19: "Consumption: undefined",
            description20: "CO2 emissions: 0 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 2406 km",
            description24: "First registration: 7/2023",
            description25: "Condition: Demonstration vehicle",
            description26: "Country of origin: Germany",
            image: "car50.jpg"
        },
        car51: {
            title: "BMW Z4 M40i sDrive 250 kW",
            price: "54 299 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: BMW",
            description4: "Model: Z4",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Brown interior",
            description8: "Interior material: Full leather interior",
            description9: "Car body: Convertible",
            description10: "Number of doors: 2/3 doors",
            description11: "Number of seats: 2",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 250 kW",
            description18: "Engine volume: 2998 cm3",
            description19: "Consumption: 8 l/100km (combined)",
            description20: "CO2 emissions: 182 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 9800 km",
            description24: "First registration: 7/2022",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car51.jpg"
        },
        car52: {
            title: "BMW X1 sDrive20i 141 kW",
            price: "26 949 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Italy",
            description3: "Brand: BMW",
            description4: "Model: X1",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Different interior color",
            description8: "Interior material: Other interior material",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: 1560 kg",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 141 kW",
            description18: "Engine volume: 1998 cm3",
            description19: "Consumption: 5.7 l/100km (combined)",
            description20: "CO2 emissions: 129 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 84 265",
            description24: "First registration: 5/2020",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car52.jpg"
        },
        car53: {
            title: "Mercedes-Benz A 180 d 85 kW",
            price: "18 499 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: France",
            description3: "Brand: Mercedes-Benz",
            description4: "Model: A 180",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: undefined",
            description8: "Interior material: undefined",
            description9: "Car body: Hatchback",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x2",
            description17: "Power: 85 kW",
            description18: "Engine volume: 1461 cm3",
            description19: "Consumption: 4 l/100km (combined) | 4.5 l/100km (city) | 3.8 l/100km",
            description20: "CO2 emissions: 107 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 138 500 km",
            description24: "First registration: 4/2019",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car53.jpg"
        },
        car54: {
            title: "Audi A7 45 TFSI quattro S tronic S-line Sportback 195 kW",
            price: "73 599 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Audi",
            description4: "Model: A7",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Partial leather interior",
            description9: "Car body: Sedan/Limousine",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Gasoline",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 195 kW",
            description18: "Engine volume: 1984 cm3",
            description19: "Consumption: 6.9 l/100km (combined)",
            description20: "CO2 emissions: 157 g/km",
            description21: "Emission class: Euro 6",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 13 242",
            description24: "First registration: 11/2023",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car54.jpg"
        },
        car55: {
            title: "Volkswagen Tiguan 2.0 TDI Life 4Motion DSG 110 kW",
            price: "27 549 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Germany",
            description3: "Brand: Volkswagen",
            description4: "Model: Tiguan",
            description5: "Body color: Gray",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: SUV/offroad",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: 5",
            description12: "Weight: undefined",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Automat",
            description16: "Drive: 4x4",
            description17: "Power: 110 kW",
            description18: "Engine volume: 1968 cm3",
            description19: "Consumption: 5 l/100km (combined)",
            description20: "CO2 emissions: 132 g/km",
            description21: "Emission class: Euro 6d",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 124 050 km",
            description24: "First registration: 2/2021",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car55.jpg"
        },
        car56: {
            title: "Ford Transit Custom 300 L2H1 VA 100 kW",
            price: "52 399 \u20AC",
            description: "VEHICLE DETAILS",
            description2: "Location: Netherlands",
            description3: "Brand: Ford",
            description4: "Model: Transit Custom",
            description5: "Body color: White",
            description6: "Color type: Metallization",
            description7: "Interior color: Black interior",
            description8: "Interior material: Fabric interior",
            description9: "Car body: Cargo VAN",
            description10: "Number of doors: 4/5 doors",
            description11: "Number of seats: undefined",
            description12: "Weight: 1836 kg",
            description13: "ENGINE",
            description14: "Fuel: Diesel",
            description15: "Gearbox: Manual",
            description16: "Drive: 4x2",
            description17: "Power: 100 kW",
            description18: "Engine volume: 1996 cm3",
            description19: "Consumption: 6.6 l/100km (combined)",
            description20: "CO2 emissions: 176 g/km",
            description21: "Emission class: No emission class",
            description22: "VEHICLE CONDITION",
            description23: "Driven: 2512 km",
            description24: "First registration: 1/2024",
            description25: "Condition: Used",
            description26: "Country of origin: undefined",
            image: "car56.jpg"
        },
    };

    const car = carDescriptions[carId];
    const modalContent = `
        <h2>${car.title}</h2>
        <img src="${car.image}" alt="${car.title}" style="max-width: 100%;">
        <h2>PRICE: ${car.price}</h2>
        <div class="car-descriptions">
            <h2>${car.description}</h2>
            <h2>${car.description13 || ''}</h2>
        </div>
        <div class="car-descriptions">
            <p>${car.description2}</p>
            <p>${car.description14 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description3}</p>
            <p>${car.description15 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description4}</p>
            <p>${car.description16 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description5}</p>
            <p>${car.description17 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description6}</p>
            <p>${car.description18 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description7}</p>
            <p>${car.description19 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description8}</p>
            <p>${car.description20 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description9}</p>
            <p>${car.description21 || ''}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description10}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description11}</p>
        </div>
        <div class="car-descriptions">
            <p>${car.description12}</p>
        </div>
        
        <div style="display: flex; width: 100%">
            <div style="width: 50%">
                    <div class="car-descriptions">
                    <h2>${car.description22}</h2>
                    </div>
                    <div class="car-descriptions">
                        <p>${car.description23}</p>
                    </div>
                    <div class="car-descriptions">
                        <p>${car.description24}</p>
                    </div>
                    <div class="car-descriptions">
                        <p>${car.description25}</p>
                    </div>
                    <div class="car-descriptions">
                        <p>${car.description26}</p>
                    </div>
            </div>
            <div style="width: 50%; display: flex; flex-direction: column; justify-content: center; align-items: center">
                <p>If you are interested</p>
                <a href="contact.html" class="contact-us-btn" style="margin: 0; display: flex">Contact us now</a>
            </div>
        </div>
    `;

    document.getElementById('car-description-content').innerHTML = modalContent;
    openModal('car-description');

}

// // Event listeners for navigation links
// document.querySelectorAll('nav a').forEach(navLink => {
//     navLink.addEventListener('click', function(event) {
//         event.preventDefault();
//         const sectionId = this.getAttribute('href').substring(1);
//         showSection(sectionId);
//     });
// });

// Generating all car items for the 'All Cars' section
const allCarsGrid = document.getElementById('allCars');

for (let i = 1; i <= 64; i++) {
    const carId = `car${i}`;
    const car = carDescriptions[carId];

    const carItem = document.createElement('div');
    carItem.classList.add('car-item');
    carItem.setAttribute('data-car-id', carId);
    carItem.onclick = () => openCarDescription(carId);

    const carImage = document.createElement('img');
    carImage.src = car.image;
    carImage.alt = car.title;
    carImage.style.maxWidth = '100%';

    const carTitle = document.createElement('h3');
    carTitle.textContent = car.title;

    const carPrice = document.createElement('p');
    carPrice.textContent = car.price;

    carItem.appendChild(carImage);
    carItem.appendChild(carTitle);
    carItem.appendChild(carPrice);

    allCarsGrid.appendChild(carItem);
}

// Generating all car items for the 'Used Cars' section
const usedCarsGrid = document.getElementById('usedCars');

for (let i = 1; i <= 10; i++) {
    const usedCarId = `usedCar${i}`;
    const car = carDescriptions[carId];

    const usedCarItem = document.createElement('div');
    usedCarItem.classList.add('car-item');
    usedCarItem.setAttribute('data-car-id', usedCarId);
    usedCarItem.onclick = () => openCarDescription(usedCarId);

    const usedCarImage = document.createElement('img');
    usedCarImage.src = usedCar.image;
    usedCarImage.alt = usedCar.title;
    usedCarImage.style.maxWidth = '100%';

    const usedCarTitle = document.createElement('h3');
    usedCarTitle.textContent = usedCar.title;

    const usedCarPrice = document.createElement('p');
    usedCarPrice.textContent = usedCar.price;

    usedCarItem.appendChild(usedCarImage);
    usedCarItem.appendChild(usedCarTitle);
    usedCarItem.appendChild(usedCarPrice);

    usedCarsGrid.appendChild(usedCarItem);
}

// Generating all car items for the 'New Arrivals' section
const newArrivalsGrid = document.getElementById('newArrivalsGrid');

// Assuming car data is stored in the same format as other sections
for (let i = 65; i <= 75; i++) { // Example for 10 new cars
    const carId = `car${i}`;
    const car = carDescriptions[carId];

    const carItem = document.createElement('div');
    carItem.classList.add('car-item');
    carItem.setAttribute('data-car-id', carId);
    carItem.onclick = () => openCarDescription(carId);

    const carImage = document.createElement('img');
    carImage.src = car.image;
    carImage.alt = car.title;
    carImage.style.maxWidth = '100%';

    const carTitle = document.createElement('h3');
    carTitle.textContent = car.title;

    const carPrice = document.createElement('p');
    carPrice.textContent = car.price;

    carItem.appendChild(carImage);
    carItem.appendChild(carTitle);
    carItem.appendChild(carPrice);

    newArrivalsGrid.appendChild(carItem);
}


function showListGroup() {
    let list = document.getElementsByClassName('list-group')[0];
    if (list.style.display === 'none' || list.style.display === '') {
        list.style.display = 'block';
    } else {
        list.style.display = 'none';
    }
}

